#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : steam-devices
Version  : 1.0.0.61
Release  : 1
URL      : https://github.com/ValveSoftware/steam-devices/archive/v1.0.0.61.tar.gz
Source0  : https://github.com/ValveSoftware/steam-devices/archive/v1.0.0.61.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: steam-devices-config = %{version}-%{release}
Patch1: 0001-Add-Makefile.patch

%description
No detailed description available

%package config
Summary: config components for the steam-devices package.
Group: Default

%description config
config components for the steam-devices package.


%prep
%setup -q -n steam-devices-1.0.0.61
cd %{_builddir}/steam-devices-1.0.0.61
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579119785
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1579119785
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/60-steam-input.rules
/usr/lib/udev/rules.d/60-steam-vr.rules
